/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LiveJobsRouteImport } from './routes/live-jobs'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as UsersSlugRouteImport } from './routes/users.$slug'
import { Route as SettingsVerificationRouteImport } from './routes/settings.verification'
import { Route as SettingsSmsRouteImport } from './routes/settings.sms'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsPlatformRouteImport } from './routes/settings.platform'
import { Route as SettingsPaymentsRouteImport } from './routes/settings.payments'
import { Route as SettingsGeoRouteImport } from './routes/settings.geo'
import { Route as SettingsEmailRouteImport } from './routes/settings.email'
import { Route as SettingsCommissionRouteImport } from './routes/settings.commission'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveJobsRoute = LiveJobsRouteImport.update({
  id: '/live-jobs',
  path: '/live-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessesRoute,
} as any)
const UsersSlugRoute = UsersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UsersRoute,
} as any)
const SettingsVerificationRoute = SettingsVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSmsRoute = SettingsSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPlatformRoute = SettingsPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentsRoute = SettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeoRoute = SettingsGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEmailRoute = SettingsEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCommissionRoute = SettingsCommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => SettingsRoute,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BusinessesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/disputes': typeof DisputesRoute
  '/fraud': typeof FraudRoute
  '/live-jobs': typeof LiveJobsRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/support': typeof SupportRoute
  '/users': typeof UsersRouteWithChildren
  '/verification': typeof VerificationRoute
  '/workers': typeof WorkersRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/settings/commission': typeof SettingsCommissionRoute
  '/settings/email': typeof SettingsEmailRoute
  '/settings/geo': typeof SettingsGeoRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/platform': typeof SettingsPlatformRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sms': typeof SettingsSmsRoute
  '/settings/verification': typeof SettingsVerificationRoute
  '/users/$slug': typeof UsersSlugRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/disputes': typeof DisputesRoute
  '/fraud': typeof FraudRoute
  '/live-jobs': typeof LiveJobsRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/support': typeof SupportRoute
  '/verification': typeof VerificationRoute
  '/workers': typeof WorkersRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/settings/commission': typeof SettingsCommissionRoute
  '/settings/email': typeof SettingsEmailRoute
  '/settings/geo': typeof SettingsGeoRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/platform': typeof SettingsPlatformRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sms': typeof SettingsSmsRoute
  '/settings/verification': typeof SettingsVerificationRoute
  '/users/$slug': typeof UsersSlugRoute
  '/businesses': typeof BusinessesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/disputes': typeof DisputesRoute
  '/fraud': typeof FraudRoute
  '/live-jobs': typeof LiveJobsRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/support': typeof SupportRoute
  '/users': typeof UsersRouteWithChildren
  '/verification': typeof VerificationRoute
  '/workers': typeof WorkersRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/settings/commission': typeof SettingsCommissionRoute
  '/settings/email': typeof SettingsEmailRoute
  '/settings/geo': typeof SettingsGeoRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/platform': typeof SettingsPlatformRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sms': typeof SettingsSmsRoute
  '/settings/verification': typeof SettingsVerificationRoute
  '/users/$slug': typeof UsersSlugRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/businesses'
    | '/disputes'
    | '/fraud'
    | '/live-jobs'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/support'
    | '/users'
    | '/verification'
    | '/workers'
    | '/businesses/$slug'
    | '/settings/commission'
    | '/settings/email'
    | '/settings/geo'
    | '/settings/payments'
    | '/settings/platform'
    | '/settings/security'
    | '/settings/sms'
    | '/settings/verification'
    | '/users/$slug'
    | '/businesses/'
    | '/settings/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/disputes'
    | '/fraud'
    | '/live-jobs'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/support'
    | '/verification'
    | '/workers'
    | '/businesses/$slug'
    | '/settings/commission'
    | '/settings/email'
    | '/settings/geo'
    | '/settings/payments'
    | '/settings/platform'
    | '/settings/security'
    | '/settings/sms'
    | '/settings/verification'
    | '/users/$slug'
    | '/businesses'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/businesses'
    | '/disputes'
    | '/fraud'
    | '/live-jobs'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/support'
    | '/users'
    | '/verification'
    | '/workers'
    | '/businesses/$slug'
    | '/settings/commission'
    | '/settings/email'
    | '/settings/geo'
    | '/settings/payments'
    | '/settings/platform'
    | '/settings/security'
    | '/settings/sms'
    | '/settings/verification'
    | '/users/$slug'
    | '/businesses/'
    | '/settings/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BusinessesRoute: typeof BusinessesRouteWithChildren
  DisputesRoute: typeof DisputesRoute
  FraudRoute: typeof FraudRoute
  LiveJobsRoute: typeof LiveJobsRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SupportRoute: typeof SupportRoute
  UsersRoute: typeof UsersRouteWithChildren
  VerificationRoute: typeof VerificationRoute
  WorkersRoute: typeof WorkersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-jobs': {
      id: '/live-jobs'
      path: '/live-jobs'
      fullPath: '/live-jobs'
      preLoaderRoute: typeof LiveJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/users/$slug': {
      id: '/users/$slug'
      path: '/$slug'
      fullPath: '/users/$slug'
      preLoaderRoute: typeof UsersSlugRouteImport
      parentRoute: typeof UsersRoute
    }
    '/settings/verification': {
      id: '/settings/verification'
      path: '/verification'
      fullPath: '/settings/verification'
      preLoaderRoute: typeof SettingsVerificationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sms': {
      id: '/settings/sms'
      path: '/sms'
      fullPath: '/settings/sms'
      preLoaderRoute: typeof SettingsSmsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/platform': {
      id: '/settings/platform'
      path: '/platform'
      fullPath: '/settings/platform'
      preLoaderRoute: typeof SettingsPlatformRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payments': {
      id: '/settings/payments'
      path: '/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof SettingsPaymentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/geo': {
      id: '/settings/geo'
      path: '/geo'
      fullPath: '/settings/geo'
      preLoaderRoute: typeof SettingsGeoRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/email': {
      id: '/settings/email'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof SettingsEmailRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/commission': {
      id: '/settings/commission'
      path: '/commission'
      fullPath: '/settings/commission'
      preLoaderRoute: typeof SettingsCommissionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof BusinessesRoute
    }
  }
}

interface BusinessesRouteChildren {
  BusinessesSlugRoute: typeof BusinessesSlugRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
}

const BusinessesRouteChildren: BusinessesRouteChildren = {
  BusinessesSlugRoute: BusinessesSlugRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
}

const BusinessesRouteWithChildren = BusinessesRoute._addFileChildren(
  BusinessesRouteChildren,
)

interface SettingsRouteChildren {
  SettingsCommissionRoute: typeof SettingsCommissionRoute
  SettingsEmailRoute: typeof SettingsEmailRoute
  SettingsGeoRoute: typeof SettingsGeoRoute
  SettingsPaymentsRoute: typeof SettingsPaymentsRoute
  SettingsPlatformRoute: typeof SettingsPlatformRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSmsRoute: typeof SettingsSmsRoute
  SettingsVerificationRoute: typeof SettingsVerificationRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCommissionRoute: SettingsCommissionRoute,
  SettingsEmailRoute: SettingsEmailRoute,
  SettingsGeoRoute: SettingsGeoRoute,
  SettingsPaymentsRoute: SettingsPaymentsRoute,
  SettingsPlatformRoute: SettingsPlatformRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSmsRoute: SettingsSmsRoute,
  SettingsVerificationRoute: SettingsVerificationRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface UsersRouteChildren {
  UsersSlugRoute: typeof UsersSlugRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersSlugRoute: UsersSlugRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  BusinessesRoute: BusinessesRouteWithChildren,
  DisputesRoute: DisputesRoute,
  FraudRoute: FraudRoute,
  LiveJobsRoute: LiveJobsRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SupportRoute: SupportRoute,
  UsersRoute: UsersRouteWithChildren,
  VerificationRoute: VerificationRoute,
  WorkersRoute: WorkersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
